apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter-deployment
  namespace: kube-prometheus-stack
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: "redis://your_redis_host:6379"  # Substitua pelo endereço do seu Redis
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: redis-exporter-configmap
              key: redis-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
