apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: kube-prometheus-stack
  labels:
    app: redis-exporter
spec:
  selector:
    matchLabels:
      app: redis-exporter
  namespaceSelector:
    matchNames:
      - kube-prometheus-stack
  endpoints:
    - port: http
      interval: 30s  # Defina o intervalo de coleta desejado