apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-service
  namespace: kube-prometheus-stack
  labels:
    app: postgres-exporter
spec:
  ports:
  - name: http
    port: 9187
    targetPort: 9187
  selector:
    app: postgres-exporter
  type: ClusterIP